### ISSUE TITLE
Debug fixation

### ISSUE THREAD

**Issue by cliffckerr** [AKraay-IDM/Rotavirus_GeneticDiversity#10]
# The situation

Originally, the model was written as functions (`rotaABM_0923_working.py`). It was refactored for speed and OOP (`rotaABM.py`), but the results are different now. In particular, before there were 4 different strains of rotavirus circulating, but in the new version, this collapses to a single strain (called "fixation"). Because the two versions of the code are so different (nearly every one of the ~1400 lines is changed), it's hard to figure out where the problem is. Plus, we expect the results to be _stochastically_ different, so we can't just check and see when things diverge.

# The problem

The results from `rotaABM.py` (~1 min runtime) should match `rotaABM_0923_working.py` (~15 min runtime), but they don't. In particular, if you run `data_cleaning.py`, the `GenoDist` dataframe has only a single row for `rotaABM.py`, whereas it should have 4.

# Some ideas for next steps
- Refactor the code so instead of writing output to a CSV file, it gets stored within the class object (see https://github.com/AKraay-IDM/Rotavirus_GeneticDiversity/issues/5)
- Integrate `data_cleaning.py` into `rotaABM.py` so we can just run one file instead of two
- Explore smaller population sizes and see how small of a population size / short of a run duration are needed to reproduce the problem
- Substitute out function-by-function / method-by-method to see if we can identify which function/method is the problem

**Comment by devclinton** [comment]
Quick update. I have so far without any luck.

- [X] Refactored the code to collect and write data as separate functions
- [X] Integrated data cleaning
- [X] Explored shorter durations and smaller population sizes. I can reproduce at duration of 5 years, and population of 10001 which is useful for debugging as comparing the two is much faster now. 
 
 To go:
- [ ] Substitute functions to see if I can find cause that way

**Comment by cliffckerr** [comment]
Closed by #9
